variable "rg" {}
variable "region" {}
variable "vault_name" {}
variable "tenant_id" {}
variable "user" {}
variable "bill_indicator_tag" {}
variable "company_code_tag" {}  
variable "env_tag" {}           
variable "consumer_org1_tag" {}
variable "consumer_org2_tag" {} 
variable "support_stat_tag" {}  